name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install project in editable mode with all dependencies
        pip install cx-Freeze

    - name: Verify structure
      run: |
        ls -R src
        test -f src/gui/gui_5_0.py || exit 1

    - name: Build executable
      run: |
        python setup.py build
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LoanChecker-${{ matrix.os }}
        path: build/*
        if-no-files-found: error
