name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install build cx_freeze

    - name: Build executable
      run: |
        python -m build --wheel --no-isolation
        pip install dist/*.whl
        cxfreeze src/gui/gui_5_0.py --target-dir dist/executable
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LoanChecker-${{ matrix.os }}
        path: dist/executable/*
        if-no-files-found: error
